### ISSUE TITLE
Strings and interpolations font-lock

### ISSUE THREAD

**Issue by dgutov** [pedz/ruby-ts-mode#2]
The result seems non-ideal to me: the string delimiters are not highlighted, and the `#{}` parts aren't either.

OTOH, I think I understand what you were aiming for: for the contents inside `#{...}` to start with the default face.

`js-ts-mode` could be used as a reference: it manages this look with a custom function, though (`js--fontify-template-string`).

![Screenshot from 2022-12-27 01-00-42](https://user-images.githubusercontent.com/271877/209587573-6e5a3c0b-d907-4724-a56c-67455e5c450f.png)

**Comment by pedz** [comment]
For font lock, set `treesit-font-lock-level` to 4 and recompute the features as the help text for `treesit-font-lock-level` describes.

Many of the faces (for me) are not colored.  setup.el in this repo sets all the faces to something (but its not pretty).

Also, look at how `treesit-font-lock-feature-list` is set in my code (towards the end of ruby-ts-mode.el).  That determines what is font locked for each level.

On top of this, you can enable and disable each "feature".  See `treesit-font-lock-recompute-features' for details.

(I may be telling you things you already know.)

**Comment by dgutov** [comment]
Okay, this rule:

```
   :language language
   :feature 'variable
   '((identifier) @font-lock-variable-name-face)
```

is not useful because it colors every identifier with variable-name-face. Random (undefined) references, method calls, even method names in method definitions. Pretty much everything that isn't highlighted by something else and isn't a special kind of token. Tree-sitter doesn't track the symbol scopes or which symbols are defined. Not in the Ruby grammar, at least.

The globals are highlighted now. But not the instance variable references -- in assignments or outside. They are a separate kind of node (`instance_variable`), so they need explicit handling.

With string delimiters - cute idea, but the face is probably not handled in most user themes. So it's probably better to follow the example of the built-in TS modes, at least for now, which only use that face for punctuation. Instead of `font-lock-punctuation-face`. :shrug:

If we're talking highlighting levels, if the default is 3, I'd put the same features in there that are already in `ruby-mode`. Then 4 would be reduced to `( bracket error operator punctuation )`. Not 100% sure about `error`, I'll have to try it out more.

**Comment by dgutov** [comment]
> Tree-sitter doesn't track the symbol scopes or which symbols are defined. Not in the Ruby grammar, at least.

Or rather, it seems like something that needs to be implemented as a separate analysis, not just font-lock rules.

**Comment by pedz** [comment]
Before we go too far down the road, I put a large comment around line 100 that explains my thoughts on how to use each of the predefined faces.

I came to this because when I submitted my first draft, I had defined two new faces and someone sorta said "Gee... why do this?"  So this gave me pause.

If it had not been for this, then I would have defined a face for each feature and liberally spewed out faces.  Then the user can precisely denote what color they want (or other characteristics) for each concept / feature that font lock provides.  e.g. there would be a ruby-ts-global-variable, ruby-ts-global-variable-assignment, ruby-ts-instance-variable,  ruby-ts-instance-variable-assignment, ...

And these would likely just inherit from one of the existing font lock faces.  And... I have little doubt if I was doing this "for myself", that is what I would have done.

So... all that to say, I crammed the faces I'm using into the 13 or so font-lock-*-face that were already defined.  Was that a mistake?

**Comment by dgutov** [comment]
> So... all that to say, I crammed the faces I'm using into the 13 or so font-lock-*-face that were already defined. Was that a mistake?

I think it was the right direction, but to have `ruby-ts-mode` look better OOTB with the default theme (as well as with other existing themes) a few more steps forward are needed. Including those that might look like oversimplifying things in the shorter term.

I.e. using `font-lock-string-face` instead of `font-lock-delimiter-face`. Maybe later it will be a good idea to define a custom derivative from the latter and use it, so that themes can override this. Or maybe we'll see themes pick up `font-lock-delimiter-face` (but the default one will need to do that first). For now, though, it's not even clear which "delimiters" the face is intended for.

And as for using `font-lock-variable-name-face` instead of `font-lock-doc-face` for variable assignments -- that's just common sense.

**Comment by dgutov** [comment]
BTW, I've brought this up on the mailing list:

https://lists.gnu.org/archive/html/emacs-devel/2022-12/msg01172.html

So we should use `font-lock-string-face` for string delimiters, until some newer face comes along.

**Comment by dgutov** [comment]
This is also resolved.
