### ISSUE TITLE
Fontification of method calls

### ISSUE THREAD

**Issue by fritzgrabo** [pedz/ruby-ts-mode#4]
Hi!

Thanks for kicking off `ruby-ts-mode`, Perry -- this is awesome! 🙌 

I'm actively following your commits and am playing around with your updates as time permits.

Doing so, I noticed that the `function` feature currently fontifies the name of a method both when it's defined, _but also when it's called_:

```elisp
   :language language
   :feature 'function
   '((call
      method: (identifier) @font-lock-function-name-face)
     (method
      name: (identifier) @font-lock-function-name-face))
```

Note that `ruby-mode` doesn't do that, and also your `notes.txt` only mention "the name after `def`".

To illustrate, here's a screenshot of `ruby-mode`:

<img width="230" alt="ruby-mode" src="https://user-images.githubusercontent.com/592734/210013389-960aba1f-07b2-450c-ad05-eaabf475562e.png">

Here's a screenshot of `ruby-ts-mode`:

<img width="230" alt="ruby-ts-mode" src="https://user-images.githubusercontent.com/592734/210013399-946f62cd-272d-47ee-92cc-9b3f0a8dfbb8.png">

Removing the `(call ...)` query makes `ruby-mode` and `ruby-ts-mode` behave the same.

I was wondering if you had added the `call` query on purpose, or if it was just an oversight really.

Personally, I'd opt for removing the query simply because in a typical Ruby file (if something like that exists), method calls are frequent enough that coloring them adds more visual noise than value. Curious what your take on this is?

Thanks!

**Comment by pedz** [comment]
Welcome!!! 👍👏

You might have seen in the other issues, I'm working my way through ruby-mode-tests.el -- trying to get all of those to pass.  I think it is "Issue 1" that has most of that particular conversation.

So... let me work my way through the test suite and then we'll circle back around and catch any other issues.  i.e. I bet this will get fixed by that point.

Also... this repo is sort of a mess right now with things scattered in ruby-ts-navigation.el, failures.el, etc.  So, if something come up undefined, it is likely in one of those files.

**Comment by fritzgrabo** [comment]
> You might have seen in the other issues, I'm working my way through ruby-mode-tests.el -- trying to get all of those to pass. I think it is "Issue 1" that has most of that particular conversation.

Yup, I had read through that one before posting, but wasn't aware that the existing `ruby-mode` tests cover fontification as well -- thanks for pointing that out. I had a quick look now and noticed that while these tests are pretty extensive and cover a wide range of cases, they don't cover the detail I raised in my original post above.

I'm happy to file a PR with some extra specs added to `ruby-mode-tests.el`, but am unsure if this is the right place to do that? Probably I should try to get those added upstream, unless you plan to add a bunch of new specs to that file in here anyway (in case `ruby-ts-mode` happens to end up next to `ruby-mode` in a single `ruby-mode.el`, similar to what Python does)?

Thanks!

**Comment by pedz** [comment]
`ruby-mode-tests.el` as well of most of what is in this repository is not really actually going to get merged into the official base.  Dmitry Gutov is putting together something that he feels can be added to the official base.  I don't know exactly how he is going to do this because I'm making lots of changes.  But... all that to say that I would file an official bug report or wait a bit.

I think the deal is that we need to get the "feature" into the official base ASAP.  Bug fixes can come over the next month or two.  Plus... there is always bug fixes into master.

You might email Dmitry Gutov and ask his suggestions.

**Comment by dgutov** [comment]
It's now in Emacs, and this issue is resolved there. Also see #5.

**Comment by fritzgrabo** [comment]
W00t! Thank you both for your work on `ruby-ts-mode`, that's awesome news! 🎉
